stages:
  - build-psuh-dockerhub
  - build-push-gitlab-registry
  - test
  - deploy
variables:
  IMAGE_NAME_DOCKERHUB: $DOCKER_USERNAME/masar-app:$CI_PIPELINE_IID
  IMAGE_NAME_GITLAB_REGISTRY:  registry.gitlab.com/$CI_PROJECT_PATH/masar-app:$CI_PIPELINE_IID
  PROJECT_NAME: masar-app
  

build-push-dockerhub:
  stage: build-psuh-dockerhub
  image: docker:24.0
  services:
    - docker:24.0-dind
  before_script:
    - docker build -t $IMAGE_NAME_DOCKERHUB .
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push $IMAGE_NAME_DOCKERHUB 

build-push-gitlab-registry:
  stage: build-push-gitlab-registry
  image: docker:24.0
  services:
    - docker:24.0-dind
  before_script:
    - docker build -t $IMAGE_NAME_GITLAB_REGISTRY .
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - docker push $IMAGE_NAME_GITLAB_REGISTRY

test_app:
  stage: test
  image: sonarsource/sonar-scanner-cli:latest

  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"

  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache

  script:
    - |
      sonar-scanner \
        -Dsonar.projectKey=$PROJECT_NAME \
        -Dsonar.projectName=$PROJECT_NAME \
        -Dsonar.sources=. \
        -Dsonar.host.url=$SONAR_HOST_URL \
        -Dsonar.login=$SONAR_TOKEN \
        -Dsonar.qualitygate.wait=true

  allow_failure: true

  only:
    - main

deploy_job:
  stage: deploy
  image:
    name: bitnami/kubectl:latest
    entrypoint: [""]
  script:
    - sed -i "s|IMAGE_PLACEHOLDER|$IMAGE_NAME_GITLAB_REGISTRY|g" deployment.yaml
    - kubectl config use-context "$KUBE_CONTEXT"
    - kubectl apply -f deployment.yaml
    - kubectl apply -f service.yaml
    - kubectl apply -f stoarge_class.yaml
    - kubectl apply -f pvc.yaml
 