stages:
  - build-psuh-dockerhub

variables:
  IMAGE_NAME: $DOCKER_USERNAME/masar-app:$CI_PIPELINE_IID


build-push-dockerhub:
  stage: build-psuh-dockerhub
  image: docker:24.0
  services:
    - docker:24.0-dind
  before_script:
    - docker build -t $IMAGE_NAME .
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push $IMAGE_NAME