apiVersion: apps/v1
kind: Deployment
metadata:
  name: masar-app-deployment
  labels:
    app: masar-app
    environment: production
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: masar-app
      environment: production
  template:
    metadata:
      labels:
        app: masar-app
        environment: production
    spec:
      imagePullSecrets:
        - name: gitlab-registry-secret
      containers:
        - name: masar-app
          image: IMAGE_PLACEHOLDER
          ports:
            - containerPort: 80
          env:
            - name: IMAGE_NAME_GITLAB_REGISTRY
              value: IMAGE_PLACEHOLDER
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          volumeMounts:
            - name: masar-app-storage
              mountPath: /app/data
      volumes:
        - name: masar-app-storage
          persistentVolumeClaim:
            claimName: efs-pvc-nodejs-app 