apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-pvc-nodejs-app
  namespace: default
  labels:
    app: nodejs-app
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 15Gi