apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  labels:
    app: nodejs-app
spec:
  selector:
      app: masar-app
      environment: production
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
